# Generated by Django 4.2.6 on 2023-10-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_alter_person_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
