# Generated by Django 4.2.6 on 2023-10-19 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_alter_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="teams.team",
            ),
        ),
    ]
